name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Fill in as much as you can — it helps us fix it faster.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Start SecureVector with `securevector-app --web`
        2. Go to ...
        3. Click ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: What should have happened?
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: How did you install SecureVector?
      options:
        - pip (securevector-ai-monitor[app])
        - Windows installer (.exe)
        - macOS installer (.dmg)
        - Linux AppImage
        - Linux DEB
        - Linux RPM
        - Source (git clone)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SecureVector version
      placeholder: "e.g. 2.1.3  (run: securevector-app --version)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS version
      placeholder: "e.g. Windows 11 22H2 / macOS 14.3 / Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version (if using pip)
      placeholder: "e.g. 3.11.2  (run: python --version)"

  - type: input
    id: agent_framework
    attributes:
      label: Agent framework (if relevant)
      placeholder: "e.g. LangChain, CrewAI, OpenClaw, Claude Desktop, n8n — or leave blank"

  - type: input
    id: llm_provider
    attributes:
      label: LLM provider / model (if relevant)
      placeholder: "e.g. OpenAI gpt-4o / Anthropic claude-opus-4-5 / Ollama llama3 — or leave blank"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any terminal output, stack traces, or browser console errors.
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and this hasn't been reported yet
          required: true
        - label: I have checked whether this issue exists in the latest version
