name: Feature Request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea that would make SecureVector better? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the situation where this would help. What are you trying to do that you can't do today?
      placeholder: "I'm trying to... but currently I have to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Who does this affect?
      options:
        - Just me
        - My team / specific use case
        - Would likely benefit most users
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      options:
        - Threat detection / rules
        - Agent tool permissions
        - LLM cost tracking
        - Proxy / integrations
        - Dashboard / UI
        - API
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and this hasn't been requested yet
          required: true
