name: Security Vulnerability
description: Report a security issue — please read before submitting
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Stop — do not report security vulnerabilities here

        Public GitHub issues are visible to everyone. Please report security vulnerabilities privately:

        - **GitHub Security Advisories (recommended):** [Report a vulnerability](https://github.com/Secure-Vector/securevector-ai-threat-monitor/security/advisories/new)
        - **Email:** security@securevector.io

        We respond within 48 hours. See our full [Security Policy](https://github.com/Secure-Vector/securevector-ai-threat-monitor/blob/master/.github/SECURITY.md) for details.

        ---

        If you're sure this is **not** a security vulnerability and just a bug, please use the [Bug Report](https://github.com/Secure-Vector/securevector-ai-threat-monitor/issues/new?template=bug_report.yml) template instead.

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I understand this is not the right place for security vulnerabilities and will use the private channels above
          required: true
